name: null
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - pip
  - python=3.7
  - future
  - pytorch=1.5
  - torchvision=0.6
  - pip: 
    - opencv-python
    - tqdm
    - Pillow
    - scipy
    - scikit-image
    - dominate