name: null
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=11.0
  - pip
  - python=3.7
  - pytorch=1.7.0
  - conda-forge::ffmpeg
  - pip: 
    - ffmpeg
    - opencv-python
    - tqdm
    - sk-video
    - moviepy